library(adespatial)
library(betapart)
library(cluster)
library(data.table)
library(dplyr)
library(geodata)
library(geodist)
library(ggcorrplot)
library(ggplot2)
library(ggspatial)
library(here)
library(magrittr)
library(purrr)
library(readxl)
library(skimr)
library(sf)
library(patchwork)
library(plyr)
library(quantreg)
library(scales)
library(sfnetworks)
library(stringr)
library(targets)
library(terra)
library(tidygraph)
library(tidyterra)
<<<<<<< HEAD
=======
library(viridis)
>>>>>>> 211ec3d728b4fd7ff26e87a0724fabca1c80eb23
library(vegan)
library(zoo)


